---

language: generic
sudo: 'required'

services:
  - docker

stages:
  - base
  - lang
  - tool

before_script:
  - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_TOKEN

jobs:
  include:
    - stage: base
      script:
      - make -C base/alpinelinux/3.11.3 snapshot
      - make -C base/alpinelinux/3.12.0 snapshot

    - stage: lang
      script:
      - make -C lang/python/3.8.0 snapshot

    - stage: tool
      script:
      - make -C tool/ansible/2.9.9 snapshot